services:
  sygrid.controller.grid:
    public: true
    class: Matt\SyGridBundle\Controller\GridController
    arguments: [ '@doctrine.orm.entity_manager' ]
    calls:
      - [ setContainer, [ '@service_container' ] ]